title: Story of a house
description:
author: adithi

baseurl: /arch

permalink: :title/


sass:
  style: compressed

include:
    - _pages



#compress.html
compress_html:
  clippings: [html,div, p, ul, td, h1, h2, h3, h4,link, meta, footer, nav, img, header, hr, br, head, style, li, ul, ol, time, main, script, title]
  comments: ["<!-- ", " -->"]
  endings: [all]
  ignore:
    envs: [local]
  blanklines: false
  profile: false
  startings: []
  
  
  
gems: 
    - jekyll-paginate
    - jemoji
    - jekyll-seo-tag